### PR TITLE
Update Travis for CMake build system

### PR DESCRIPTION
**Pull request by wxmerkt**

### CODE REVIEW

**Comment by rdeits** [comment]
It may be possible to make the travis build even simpler than this, if you're interested. I'm building bot_core_lcmtypes inside https://github.com/rdeits/BotCoreLCMTypes.jl by just building a local copy of LCM, and then just setting `-DCMAKE_PREFIX_PATH` to point to that local LCM copy when I build bot_core_lcmtypes. That means no changes to PATH, LD_LIBRARY_PATH, PKG_CONFIG_PATH, etc. If you're interested, I could try to push a commit here to see if I can make it work?

**Comment by wxmerkt** [comment]
That would be amazing, thank you!

**Comment by patmarion** [comment]
Or we could switch to USE_SYSTEM_{LCM,PCL,OPENCV} to be ON by default.  Has that been discussed recently?

**Comment by rdeits** [comment]
@wxmerkt no problem! I just spent this afternoon figuring out how to do this already, so there's no need for you to suffer too ;-). 

@patmarion I didn't know we had that option. Is that part of the new cmake build?

**Comment by rdeits** [comment]
ok, done

**Comment by wxmerkt** [comment]
@rdeits Thanks, that's awesome :)

@patmarion Vlad and I discussed it this afternoon to switch PCL to ON by default and perhaps LCM as well so we bundle a oh preferred master compatible LCM version. Maybe need a further brief discussion regarding that but would be great in general

**Pull request merged**
