### PR TITLE
CMake modernization

### PR DESCRIPTION
**Pull request by mwoehlke-kitware**
This replaces PODS build logic with modern CMake patterns, including:
- Use modern CMake rules to build Java code rather than doing it "by hand".
- Use CMake-ified LCM¹ and imported targets from the same.
- Use the new LCM Use file (from CMake-ified LCM) to generate code from the LCM type files.
- Create a CMake package configuration file with exported targets (including the JAR).

This drastically simplifies things for downstream consumers and is the officially preferred way to consume packages in CMake-built projects.

(¹ https://github.com/RobotLocomotion/lcm/tree/cmake)

### CODE REVIEW

**Comment by mwoehlke-kitware** [comment]
> This drastically simplifies things for downstream consumers...

To illustrate:

### Old code:

```
find_package(PkgConfig)
pkg_check_modules(BOT2-CORE lcmtypes_bot2-core)
include_directories(${BOT2-CORE_INCLUDE_DIRS})
link_directories(${BOT2-CORE_LIBRARY_DIRS})
target_compile_options(mylib ${BOT2-CORE_CFLAGS})
target_link_libraries(mylib ${BOT2-CORE_LIBRARIES})

pkg_check_modules(BOT2-CORE lcmtypes_bot2-core-java)
set(CMAKE_JAVA_INCLUDE_PATH
  ${BOT2-CORE-JAVA_CLASSPATH}
  ${CMAKE_JAVA_INCLUDE_PATH})
add_jar(myjar SOURCES ${java_sources})
```

### New code:

```
find_package(bot2-core)
target_link_libraries(mylib lcmtypes_bot2-core)
add_jar(myjar SOURCES ${java_sources} INCLUDE_JARS lcmtypes_bot2-core-jar)
```

---

In particular, only a single package search is now required (and Windows users don't need to obtain pkgconfig), and the mechanism for specifying a non-standard location is built into CMake (set `bot2-core_DIR`), rather than requiring an environment variable. Using the library is trivial; simply linking to the imported target takes care of adding compile options¹ and include directories. Using the JAR is equally trivial.

(¹ We don't actually have compile options at the moment, but shown for completion / correctness. With exported targets, if compile flags are ever added, users will automagically pick them up without needing to change anything on their end.)

**Comment by mwoehlke-kitware** [comment]
> ...CMake-ified LCM... (https://github.com/RobotLocomotion/lcm/tree/cmake)

To clarify: we fully intended to submit the LCM changes to upstream. However, it is still a work in progress (some bits that aren't needed by us aren't yet built by CMake).

To [Drake](http://drake.mit.edu/) folk following along: the intent is to move Drake to this branch when possible. (Since the pkgconfig file is dropped, all consumers need to be ported also. I'll be working on that, but between when this lands and when said work is completed, we'll need to refrain from updating this package in Drake.)

**Comment by mauricefallon** [comment]
I'm sorry but I don't have the time presently to understand the implications of this.

As you are probably aware bot_core_lcmtypes is used in the OpenHumanoids project which is a continuation of the MIT DRC project. Pods are themselves used in many of our sub projects.

I guess I need to know more about the motivations of doing this and possibly some help in bringing this change through to our system.

**Comment by mwoehlke-kitware** [comment]
Drake is in the process of eliminating pods; we're finding that it is frequently more trouble than benefit. We've also had multiple issues related to how LCM is built and used that are addressed by the CMake-ified LCM. In particular, trying to maintain copies of the logic to generate code from the LCM type files (i.e. `lcm.cmake`) is problematic, and LCM itself is difficult to build on platforms that don't natively provide glib (see e.g. comments in RobotLocomotion/drake#2118). The CMake package configurations also allow the installed package to be relocatable, unlike the pkg-config files. They _also_ permit (when set up correctly, which this branch does) the package to be consumed from a build tree without requiring it to actually be installed; again, something that pkg-config can't support.

As another example, compare what happens when I try to use a built-but-not-installed lcm to build _this_ project...

### Old code:
1. run cmake
   - can't find lcm: lcm types will not be built (..._not_ a hard error?)
2. set `PKG_CONFIG_PATH`
   - LCM_GEN_EXECUTABLE-NOTFOUND: command not found
3. _manually_ set `LCM_GEN_EXECUTABLE`
   - build fails because lcm isn't installed

### New code:
1. run cmake
   - can't find lcm: _hard error_ (as it should be!)
2. set `lcm_DIR` to built-but-not-installed lcm
   - successful build!

I'm sure this is less painful if lcm is provided by the system (i.e. already in `PATH` and `PKG_CONFIG_PATH`), but if the install is in a non-standard location, the new way is still much less painful for the user when building bot_core_lcmtypes itself. If lcm is provided by the system, or already in `CMAKE_PREFIX_PATH` (which serves a similar purpose to `PKG_CONFIG_PATH`), the new way is (also) fully automatic; if not, it gives a very nice error message, including telling you exactly how to fix the problem. (The message comes from CMake itself, since we're looking for lcm using the standard and preferred CMake mechanism to look for a package.)

---

I'm not as familiar with the DRC ecosystem; to better my own understanding, how many _non_-CMake projects need to consume bot_core_lcmtypes? Would converting these to CMake be a feasible solution? Switching CMake projects _should_ be straight-forward (although experience with Drake suggests that build logic for pods projects can be surprisingly obtuse), and _very likely_ will result in much improved build logic (see e.g. the previously given example; the pods equivalent of the 'old style' is even worse).

**Comment by mauricefallon** [comment]
Hi again, after thinking about this over the weekend, I'm going say that we cannot take on this change.
I think that what you are suggesting would bring improvements and certainly more modern.

The issue is the we do not have any software engineers working on the openhumanoids project to carry it though our ecosystem. (Compared to the drake, the project is tiny.)

I think the preferred route might be for drake to avoid using this lcmtypes repository.

**Comment by mwoehlke-kitware** [comment]
Is the problem just the backwards compatibility? I have been investigating continuing to provide a `.pc` for compatibility (CMake-ified LCM is doing this now)...

**Comment by wxmerkt** [comment]
@mwoehlke-kitware Thank you very much, I'd love to get this merged in and am currently assessing how it affects downstream after the pkg-config backwards compatibility fix as well as new projects. 

I stumbled upon the same issue as described in https://github.com/RobotLocomotion/drake/issues/3351 and wonder what the correct solution would be to streamline downstream changes to a minimum. I'm using your more recent https://github.com/mwoehlke-kitware/bot_core_lcmtypes/commit/6f8d14dc2f810aaf995c640518e6c3431179de98 commit by the way.

CMakeLists.txt:
```
cmake_minimum_required(VERSION 2.8 FATAL_ERROR)

project(test_bot_core_lcmtypes)

find_package(lcm REQUIRED)
find_package(bot2-core REQUIRED)

get_cmake_property(_variableNames VARIABLES)
foreach (_variableName ${_variableNames})
    message(STATUS "${_variableName}=${${_variableName}}")
endforeach()

if (${bot2-core_FOUND})
    message(WARNING "found it")
    message(WARNING ${bot2-core_INCLUDE_DIRS})
endif()

add_executable(test_bot_core_lcmtypes main.cc)
target_link_libraries(test_bot_core_lcmtypes lcm lcmtypes_bot2-core)
```

If I now include any bot_core lcm header that references another header, it fails to find them (INCLUDE_DIRS missing?)

Printing all CMake variables related to bot2-core:
```
-- bot2-core_CONFIG=/home/wxm/dev/oh-distro-private/software/build/lib/bot2-core/cmake/bot2-coreConfig.cmake
-- bot2-core_CONSIDERED_CONFIGS=/home/wxm/dev/oh-distro-private/software/build/lib/bot2-core/cmake/bot2-coreConfig.cmake
-- bot2-core_CONSIDERED_VERSIONS=unknown
-- bot2-core_DIR=/home/wxm/dev/oh-distro-private/software/build/lib/bot2-core/cmake
-- bot2-core_FOUND=1
-- bot2-core_VERSION_COUNT=0
-- bot2-core_VERSION_MAJOR=0
-- bot2-core_VERSION_MINOR=0
-- bot2-core_VERSION_PATCH=0
-- bot2-core_VERSION_TWEAK=0
```

**Pull request merged**
