### PR TITLE
Workaround to fix build failures on windows.

### PR DESCRIPTION
**Pull request by jhoare**
- Made lcm not REQUIRED
- Disabled java portion

### CODE REVIEW

**Comment by RussTedrake** [comment]
why not require lcm?  was it failing because of a problem w/ pkg config?

**Comment by jhoare** [comment]
Yeah on windows its failing to find LCM, but still does find lcm-gen and continues on. I agree it should be required, but this is the quickest thing to get the builds going again.

**Comment by RussTedrake** [comment]
understood

**Comment by patmarion** [comment]
I think that the java module is required in openhumanoids.  Assuming this change is only temporary, ok.  You might also wrap that java part with an if(NOT WIN32) ... endif()

**Comment by jhoare** [comment]
@patmarion Good point I'll do that now.

**Comment by RussTedrake** [comment]
or we could really merge the drake fix off your fork. as long as we follow
through and resolve this properly.

**Comment by jhoare** [comment]
@RussTedrake That would be fine with me but I'll leave it up to you. Either way we'll want to document this problem and make sure we get it resolved correctly.

**Comment by RussTedrake** [comment]
Let’s merge from your fork, resolve it soundly on our end, then push to
open-humanoids.

**Comment by mauricefallon** [comment]
@patmarion : the java modules are the quick view options you get when right clicking on an image or lidar channel in the spy - to view the lidar wedge and the image. This would not disable the java lcm bindings.

**Comment by jhoare** [comment]
Look at #3

**Pull request closed without merging**
